baseURL = "http://www.example.com"
title = "3DIA"
theme = "hugo-coder"
themesDir ="../.."
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true


[params]
author = "Project 3DIA"
description = "A new dimension for the diagnosis of spatial neglect"
keywords = "VR, neglect, diagnostics"
info = ["A new dimension for the diagnosis of spatial neglect"]
avatarURL = "images/3dia-logo-v2.0_logo-only.png"
# gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2021
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# [[params.social]]
# name = "Github"
# icon = "fa fa-2x fa-github"
# weight = 1
# url = "https://github.com/johndoe/"

[[params.social]]
name = "Gitlab"
icon = "fa fa-2x fa-gitlab"
weight = 2
url = "https://gitlab.gwdg.de/3dia"

# [[params.social]]
# name = "Notion"
# icon = "fa fa-2x fa-github"
# weight = 7
# url = "https://gitlab.gwdg.de/3dia"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/Project3DIA"

# [[params.social]]
# name = "LinkedIn"
# icon = "fa fa-2x fa-linkedin"
# weight = 4
# url = "https://www.linkedin.com/in/johndoe/"

# [[params.social]]
# name = "Medium"
# icon = "fa fa-2x fa-medium"
# weight = 5
# url = "https://medium.com/@johndoe"

# [[params.social]]
# name = "RSS"
# icon = "fa fa-2x fa-rss"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "News"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Team"
weight = 3
url = "team/"

[[languages.en.menu.main]]
name = "Contact us"
weight = 5
url = "contact/"

[languages.de]
languageName = ":de:"
title = "Projekt 3DIA"

[languages.de.params]
author = "Projekt 3DIA"
info = "Neue Dimensionen für die Diagnostik räumlichen Neglects."
description = "Website des Projekts 3DIA."
keywords = "VR, Räumlicher Neglect, Diagnostik"

[[languages.de.menu.main]]
name = "Über uns"
weight = 1
url = "about/"

[[languages.de.menu.main]]
name = "News"
weight = 2
url = "posts/"

[[languages.de.menu.main]]
name = "Team"
weight = 3
url = "team/"

[[languages.de.menu.main]]
name = "Kontakt"
weight = 5
url = "contact/"
